Luxtorpeda DOES require one dependency when building from source.
```bash
pm@Velvet4Renaissance:~/luxtorpeda$ make user-install
cargo build
   Compiling openssl-sys v0.9.48
   Compiling idna v0.1.5
   Compiling rand_chacha v0.1.1
   Compiling backtrace-sys v0.1.31
   Compiling miniz_oxide_c_api v0.2.3
   Compiling lzma-sys v0.1.15
   Compiling parking_lot_core v0.4.0
   Compiling bytes v0.4.12
   Compiling mio v0.6.19
   Compiling hyper v0.12.33
error: failed to run custom build command for `openssl-sys v0.9.48`

Caused by:
  process didn't exit successfully: `/home/pm/luxtorpeda/target/debug/build/openssl-sys-93434b38d6dc981f/build-script-main` (exit code: 101)
--- stdout
cargo:rustc-cfg=const_fn
cargo:rerun-if-env-changed=X86_64_UNKNOWN_LINUX_GNU_OPENSSL_LIB_DIR
X86_64_UNKNOWN_LINUX_GNU_OPENSSL_LIB_DIR unset
cargo:rerun-if-env-changed=OPENSSL_LIB_DIR
OPENSSL_LIB_DIR unset
cargo:rerun-if-env-changed=X86_64_UNKNOWN_LINUX_GNU_OPENSSL_INCLUDE_DIR
X86_64_UNKNOWN_LINUX_GNU_OPENSSL_INCLUDE_DIR unset
cargo:rerun-if-env-changed=OPENSSL_INCLUDE_DIR
OPENSSL_INCLUDE_DIR unset
cargo:rerun-if-env-changed=X86_64_UNKNOWN_LINUX_GNU_OPENSSL_DIR
X86_64_UNKNOWN_LINUX_GNU_OPENSSL_DIR unset
cargo:rerun-if-env-changed=OPENSSL_DIR
OPENSSL_DIR unset
run pkg_config fail: "`\"pkg-config\" \"--libs\" \"--cflags\" \"openssl\"` did not exit successfully: exit code: 1\n--- stderr\nPackage openssl was not found in the pkg-config search path.\nPerhaps you should add the directory containing `openssl.pc\'\nto the PKG_CONFIG_PATH environment variable\nNo package \'openssl\' found\n"

--- stderr
thread 'main' panicked at '

Could not find directory of OpenSSL installation, and this `-sys` crate cannot
proceed without this knowledge. If OpenSSL is installed and this crate had
trouble finding it,  you can set the `OPENSSL_DIR` environment variable for the
compilation process.

Make sure you also have the development packages of openssl installed.
For example, `libssl-dev` on Ubuntu or `openssl-devel` on Fedora.

If you're in a situation where you think the directory *should* be found
automatically, please open a bug at https://github.com/sfackler/rust-openssl
and include information about your system as well as this message.

$HOST = x86_64-unknown-linux-gnu
$TARGET = x86_64-unknown-linux-gnu
openssl-sys = 0.9.48

', /home/pm/.cargo/registry/src/github.com-1ecc6299db9ec823/openssl-sys-0.9.48/build/find_normal.rs:150:5
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace.

warning: build failed, waiting for other jobs to finish...
error: build failed
Makefile:37 : la recette pour la cible « build » a échouée
make: *** [build] Erreur 101
```

To be fair, I´m using deepin 15.11, which has it´s own debian repo, but is usually more outdated, so it this might be preinstalled on more ¨updated¨ distros like those.
I wasn´t sure if the package name was the exact one on OpenSUSE and Manjaro/Arch so i didn´t added those.

If this sound more of an issue, I´ll open one for it if needed.